### ISSUE TITLE
DNS Server

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/nest#17]
In order to be able to manage our own DNS and issue certificates, we'll need to host our own DNS server and migrate current entries from hackclub/dns.

An alternative would be to setup a separate DNSimple account

**Comment by ajsirota** [comment]
Setting up our own DNSimple account seems like the simplest option. Would HQ cover it? Or would it be taken out of the Nest HCB?

**Comment by alx-alexpark** [comment]
https://www.knot-dns.cz/

**Comment by polypixeldev** [comment]
Problem solved in favor of just using hackclub/dns
