### ISSUE TITLE
slack signup flow

### ISSUE THREAD

**Issue by benharri** [hackclub/nest#2]
send desired username in `#hack-as-a-service-signup`

bot will respond in thread and ask for ssh pubkey
validate both available and send off `adduser` command

**Comment by polypixeldev** [comment]
@cskartikey

**Comment by ajsirota** [comment]
We could ask to load the pubkeys from your GitHub account - everyone's keys are available at https://github.com/%USERNAME.keys

**Comment by polypixeldev** [comment]
We could do that! If we have their GitHub username, then we could actually just automatically load them whenever they try to ssh, which is useful ig if their keys change
