### ISSUE TITLE
Limitations page typo

### ISSUE THREAD

**Issue by opticaldrive** [hackclub/nest#43]
https://guides.hackclub.app/index.php/Limitations
> Use more than 15GB of disk space. If you require more or less disk space than this, you may ask the Nest admins.
>Use more than 2GB of RAM. If you require more or less disk space than this, you may ask the Nest admins.
Should be RAM for the second?
Thanks.

**Comment by cskartikey** [comment]
Yeah. 
I think you can edit it through media wiki

**Comment by opticaldrive** [comment]
Wasn’t aware I could do that, appears as locked to me.

**Comment by cskartikey** [comment]
Closing this as it has been resolved.

**Comment by opticaldrive** [comment]
Thank you
