### ISSUE TITLE
DNS challenge for *.hackclub.app tls cert

### ISSUE THREAD

**Issue by benharri** [hackclub/nest#8]

**Comment by benharri** [comment]
https://caddyserver.com/docs/automatic-https#wildcard-certificates

**Comment by polypixeldev** [comment]
https://github.com/hackclub/dns/issues/980

**Comment by polypixeldev** [comment]
Requires #17

**Comment by polypixeldev** [comment]
Solved in favor of just using hackclub/dns, so not needed.
