### ISSUE TITLE
custom domain support

### ISSUE THREAD

**Issue by benharri** [hackclub/nest#9]
https://caddy.community/t/serving-tens-of-thousands-of-domains-over-https-with-caddy/11179

will need to run a localhost app to check dns and existence of app directory under `~/pub`

**Comment by alx-alexpark** [comment]
We will need to re-plan this due to our differently structured architecture.

**Comment by polypixeldev** [comment]
#11

**Comment by hello-smile6** [comment]
Was this resolved by #28?

**Comment by polypixeldev** [comment]
yes, thanks!
